version: "3"
services:
  springboot-mongodb-docker-mongodb:
    image: mongo:latest
    container_name: "springboot-mongodb-docker-mongodb"
    ports:
      - 27017:27017
  springboot-mongodb:
    image: springboot-mongodb:1.0
    container_name: springboot-mongodb
    ports:
      - 8080:8080
    links:
      - springboot-mongodb-docker-mongodb